package wang.relish.ledger.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import wang.relish.ledger.bean.Benefit;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "BENEFIT".
 */
public class BenefitDao extends AbstractDao<Benefit, Long> {

    public static final String TABLENAME = "BENEFIT";

    /**
     * Properties of entity Benefit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Pid = new Property(1, long.class, "pid", false, "PID");
        public final static Property Date = new Property(2, long.class, "date", false, "DATE");
        public final static Property Benefit = new Property(3, long.class, "benefit", false, "BENEFIT");
    }


    public BenefitDao(DaoConfig config) {
        super(config);
    }

    public BenefitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"BENEFIT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"PID\" INTEGER NOT NULL ," + // 1: pid
                "\"DATE\" INTEGER NOT NULL ," + // 2: date
                "\"BENEFIT\" INTEGER NOT NULL );"); // 3: benefit
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BENEFIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Benefit entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPid());
        stmt.bindLong(3, entity.getDate());
        stmt.bindLong(4, entity.getBenefit());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Benefit entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPid());
        stmt.bindLong(3, entity.getDate());
        stmt.bindLong(4, entity.getBenefit());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    @Override
    public Benefit readEntity(Cursor cursor, int offset) {
        Benefit entity = new Benefit( //
                cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // pid
                cursor.getLong(offset + 2), // date
                cursor.getLong(offset + 3) // benefit
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Benefit entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPid(cursor.getLong(offset + 1));
        entity.setDate(cursor.getLong(offset + 2));
        entity.setBenefit(cursor.getLong(offset + 3));
    }

    @Override
    protected final Long updateKeyAfterInsert(Benefit entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Benefit entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Benefit entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
