package wang.relish.ledger.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import wang.relish.ledger.bean.Benefit;
import wang.relish.ledger.bean.Project;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig benefitDaoConfig;
    private final DaoConfig projectDaoConfig;

    private final BenefitDao benefitDao;
    private final ProjectDao projectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        benefitDaoConfig = daoConfigMap.get(BenefitDao.class).clone();
        benefitDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        benefitDao = new BenefitDao(benefitDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);

        registerDao(Benefit.class, benefitDao);
        registerDao(Project.class, projectDao);
    }

    public void clear() {
        benefitDaoConfig.clearIdentityScope();
        projectDaoConfig.clearIdentityScope();
    }

    public BenefitDao getBenefitDao() {
        return benefitDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

}
